// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZp1ZyV8FQN_TW-6zaB1fYTGECAInNQ0',
    appId: '1:604367160297:web:2fc1b789980c233959c178',
    messagingSenderId: '604367160297',
    projectId: 'salaryfits-ps',
    authDomain: 'salaryfits-ps.firebaseapp.com',
    storageBucket: 'salaryfits-ps.appspot.com',
    measurementId: 'G-0WR2D9DJR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5R1AJEZJwBlxEbb5kZBmRS6-A87VC8lw',
    appId: '1:604367160297:android:3d37f7db849f521d59c178',
    messagingSenderId: '604367160297',
    projectId: 'salaryfits-ps',
    storageBucket: 'salaryfits-ps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZwULZScBgNIxJK3zXLV-fA2Po_w_iptE',
    appId: '1:604367160297:ios:86e9c224a622bdaf59c178',
    messagingSenderId: '604367160297',
    projectId: 'salaryfits-ps',
    storageBucket: 'salaryfits-ps.appspot.com',
    iosClientId: '604367160297-hpfrq3or0qf2rjk221i7njf5nv6jttoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.salaryfitsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZwULZScBgNIxJK3zXLV-fA2Po_w_iptE',
    appId: '1:604367160297:ios:86e9c224a622bdaf59c178',
    messagingSenderId: '604367160297',
    projectId: 'salaryfits-ps',
    storageBucket: 'salaryfits-ps.appspot.com',
    iosClientId: '604367160297-hpfrq3or0qf2rjk221i7njf5nv6jttoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.salaryfitsFlutter',
  );
}
